#!/usr/bin/env bash

javac -cp src/libs/jackson-annotations-2.9.3.jar:src/libs/jackson-core-2.9.3.jar:src/libs/jackson-databind-2.9.3.jar src/*.java

jar cfm Main.jar Manifest.txt src/Main.class src/libs/jackson-annotations-2.9.3.jar src/libs/jackson-core-2.9.3.jar src/libs/jackson-databind-2.9.3.jar src/*.class

java -jar  src/Main.jar db.json


