#!/usr/bin/env bash
cd src

javac -cp libs/jackson-annotations-2.9.3.jar:libs/jackson-core-2.9.3.jar:libs/jackson-databind-2.9.3.jar *.java

jar cfm Main.jar Manifest.txt Main.class libs/jackson-annotations-2.9.3.jar libs/jackson-core-2.9.3.jar libs/jackson-databind-2.9.3.jar Group.class

java -jar  Main.jar ../db.json


